### ISSUE TITLE
Error "No space left on device"

### ISSUE THREAD

**Issue by astraw** [passcod/notify#103]
Hi, I'm having trouble getting the example `monitor_debounced` to run without error on linux (kernel 3.16 debian amd64) compiled with rustc 1.13.0.

It seems to run fine on most directories on my filesystem (ZFS from zfsonlinux.org), but there are at least two directories where I get a "No space left on device" error. The distinguishing feature of these directories is that there are many files and subdirectories (e.g. hundreds of thousands of files and tens of thousands of subdirectories).

The thing is, I don't know what device should have no space left. The filesystem in question has 45 TB free and the root filesystem (with /tmp) has 97 GB free. Also, diving into the code I don't see any temporary file allocations. Any hints on what's behind this and how to debug it?

```
# ./monitor_debounced plots
watching plots
error: Io(Error { repr: Os { code: 28, message: "No space left on device" } })
```

**Comment by dfaust** [comment]
It's inotify's way of saying that the watch limit has been reached. (Having a dedicated error type for that case in rsnotify might be a good thing though.)
Have a look at http://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached for more information about the inotify watch limit and how to raise it.

**Comment by astraw** [comment]
Thanks, that makes sense.

I'm not sure that a dedicated error type or error handling is needed. In this case, errno is set to `ENOSPC` by the system call, which seems totally reasonable. (And is described in the man page for `inotify_add_watch` as "The user limit on the total number of inotify watches was reached or the kernel failed to allocate a needed resource.").

I was confused by the std::fmt::Debug implementation of std::io::Error, which is where the "No space left on device" message comes from.

Perhaps it could be argued that inotify_add_watch should have used a specialized errno, but that ship has sailed.
