### ISSUE TITLE
No notifications at all after saving a file twice in Vim.

### ISSUE THREAD

**Issue by jmatraszek** [passcod/notify#113]
This might be related to #101.

I am using `notify 4.0.0`, `rustc 1.15.0`, `linux 4.4.46-1-lts` (Arch Linux).

Watching the file like this:
```
    let (tx_watcher, rx_watcher) = channel();
    let mut watcher: RecommendedWatcher = try!(Watcher::new(tx_watcher, Duration::from_secs(1)));
    try!(watcher.watch(config_file, RecursiveMode::NonRecursive)); // NonRecursie as we only watch config file
```
Then processing the events like this (I know it can be written more Rust-way;)):
```
   if let Some(ref rx_watcher) = rx_watcher {
            'watch: loop {
                match rx_watcher.recv() {
                info!("Waiting for event to be received!");
                    Ok(event) => {
                        info!("Event: {:?}", event);
                        match event {
                            Create(_) | Write(_) => {
                                _iron.close().expect("Iron cannot be closed");
                                thread::sleep(Duration::from_secs(1));
                                break 'watch
                            },
                            _ => continue 'watch
                        }
                    },
                    Err(e) => error!("watch error: {:?}", e),
                }
            }
        }
```

When I save a file in Vim twice I get:
```
09:32:21 [INFO] Waiting for event to be received!
09:32:24 [INFO] Event: NoticeRemove("/home/jakub/depot/haxonite/target/debug/config.toml")
09:32:24 [INFO] Waiting for event to be received!
09:32:25 [INFO] Event: Create("/home/jakub/depot/haxonite/target/debug/config.toml")
09:32:26 [INFO] Waiting for event to be received!
09:32:30 [INFO] Event: NoticeRemove("/home/jakub/depot/haxonite/target/debug/config.toml")
09:32:30 [INFO] Waiting for event to be received!
09:32:31 [INFO] Event: Remove("/home/jakub/depot/haxonite/target/debug/config.toml")
09:32:31 [INFO] Waiting for event to be received!
```
After that no new events arrive on the channel (even if I open the file in other editor and save it from there).

After restarting my application and editing a file just in `nano` I get this:
```
09:24:35 [INFO] Waiting for event to be received!
09:24:45 [INFO] Event: NoticeWrite("/home/jakub/depot/haxonite/target/debug/config.toml")
09:24:45 [INFO] Waiting for event to be received!
09:24:46 [INFO] Event: Write("/home/jakub/depot/haxonite/target/debug/config.toml")
09:24:47 [INFO] Waiting for event to be received!
09:24:51 [INFO] Event: NoticeWrite("/home/jakub/depot/haxonite/target/debug/config.toml")
09:24:51 [INFO] Waiting for event to be received!
09:24:52 [INFO] Event: Write("/home/jakub/depot/haxonite/target/debug/config.toml")
09:24:53 [INFO] Waiting for event to be received!
```
and so on, events keep arriving on the channel.

**Comment by passcod** [comment]
Right, so what your Vim did is remove the file and create a new one. Nano just writes to the file. Some editors do the one, some do the other, some do either one depending on circumstance.

The issue with remove-then-create is to do with how files actually work. Simplified, files are a named (the path + filename) pointer to some data blob on disk (called the inode). You can see that a little better by creating a hardlink, i.e. adding a different named pointer for the same data blob. Edit one, the other will have the same content.

Where it applies to us is that while notify, and most particularly, the kernel API it's using as a backend (inotify in this case), takes a _path_ for convenience, it really watches _inodes_. When it creates the watch on a file, it resolves the path to its inode and then waits for events on that.

When Nano writes to the file, then it emits Write events as normal. But when Vim deletes the file, it emits the Remove... and then the inode ceases to exist. A new one is created pointed to by the same name, yes, and events are probably happening there, sure, but we're not watching that. This is how filesystems work and is _not a bug_.

Now, there's two solutions to that: either use PollWatcher, which _does_ watch paths and not inodes. Or watch _the folder_ containing that `config.toml` file, and filter the events to only those regarding the config file.

**Comment by jmatraszek** [comment]
Thanks for the explanation! And sorry for the false alarm, I was not aware how the internals on notify work. Anyway, implemented this using watching whole directory and matching on the filename.
