### ISSUE TITLE
Deadlock due to race in FsEventWatcher

### ISSUE THREAD

**Issue by michaelfairley** [passcod/notify#118]
Because the runloop thread [signals that the runloop has started _before_ `CFRunLoopStart` is called](https://github.com/passcod/notify/blob/80594cf6aec242a0986c45ffc31ff692d30d1698/src/fsevent.rs#L208-L210), it's possible for [`CFRunLoopStop` to get called](https://github.com/passcod/notify/blob/80594cf6aec242a0986c45ffc31ff692d30d1698/src/fsevent.rs#L102) _before_ `CFRunLoopStart`, causing the runloop to never stop and thus [the `done` channel to be waited on forever](https://github.com/passcod/notify/blob/80594cf6aec242a0986c45ffc31ff692d30d1698/src/fsevent.rs#L109).

In practice, if I have two `watch` commands back to back, I get a deadlock roughly 10% of the time on my Mac.

I have a [somewhat cheesy workaround](https://github.com/michaelfairley/notify/commit/7fd41b3a0a47be4f4013750bd74b0829109db3cd) that I'm using right now, but an ideal solution probably involves `CFRunLoopObserver` or somesuch.

**Comment by cmyr** [comment]
I think this bug is serious enough that the proposed patch should be accepted. I'm not sure it's worth making major changes to `FsEventWatcher` when #117 will probably require another one. @passcod do you have any thoughts?

**Comment by passcod** [comment]
@michaelfairley are you okay with me using your workaround?

**Comment by michaelfairley** [comment]
Yes! Please do! It's been working well enough for me since I initially filed this issues.

**Comment by cmyr** [comment]
@michaelfairley are you in a position to PR your patch? If not I can, save @passcod the time.

**Comment by passcod** [comment]
Done with #134
