### ISSUE TITLE
Huge memory leak (and deadlock?) after multiple RESCAN events

### ISSUE THREAD

**Issue by mersinvald** [passcod/notify#119]
I ran that problem on Linux when I tried to recursively watch directory with a lot of IO (active rls rebuilding a project with lots of dependencies)

When a lot of rescans are being sent, `notify` leaks memory and CPU locks on 100% load. Also in such state NotifyWrite/NotifyRead events do not finish with Write/Read events, even though I have a 1ms timer duration for watcher.

In my case `notify` thread ate 729M of resources and whole CPU core. With higher debounce delay (30 sec) it consumed memory until OOM killer killed the process.

### How to reproduce:
Take any cargo project with lots of dependencies and run example programm to watch it:

```
extern crate notify;

use notify::{Watcher, RecursiveMode, watcher};
use std::sync::mpsc::channel;
use std::time::Duration;

fn main() {
    let (tx, rx) = channel();

    // you can use Duration::from_millis(1) here
    let mut watcher = watcher(tx, Duration::from_secs(10)).unwrap();

    watcher.watch("/home/user/path_to_project", RecursiveMode::Recursive).unwrap();

    loop {
        match rx.recv() {
           Ok(event) => println!("{:?}", event),
           Err(e) => println!("watch error: {:?}", e),
        }
    }
}
```

Run `cargo clean && cargo build` in the watching project.

**Comment by passcod** [comment]
You'll probably want to go for the non-debounced API, which shouldn't exhibit this, at least until that's resolved.

**Comment by passcod** [comment]
I *think* this shouldn't happen with the way v5 will work, but as I haven't written that part yet I can't be sure. Leaving myself this note to make sure I write tests for scenarios like this.

**Comment by mersinvald** [comment]
@passcod thanks, I'll test it and will let you know here

**Comment by passcod** [comment]
I believe that has been fixed.
