### ISSUE TITLE
Suitability with futures mpsc/cpu_pool

### ISSUE THREAD

**Issue by xrl** [passcod/notify#120]
I'd like to use the future mpsc with notify so I can get something similar to http://hermanradtke.com/2017/03/03/future-mpsc-queue-with-tokio.html working. I want something that has the futures interface so I can easily plug it in without a dedicated thread for receiving events. Does that seem reasonable?

**Comment by passcod** [comment]
Can you look at the proposed design in #117 to see if that would help?

**Comment by passcod** [comment]
This will be done in v5.

**Comment by passcod** [comment]
Closing in favour of main tracking issue.
