### ISSUE TITLE
Better Debug instance for Op

### ISSUE THREAD

**Issue by xrl** [passcod/notify#121]
Could we make it so the "{:?}" formatting for an Op actually shows something? On Mac OS X it's an empty string. I have to do the following to make it better:

```rust
println!("'WRITE: {:?}' 'REMOVE: {:?}' 'CREATE: {:?}' '{:?}' ('{:?}')", op.contains(op::WRITE), op.contains(op::REMOVE), op.contains(op::CREATE), path, cookie)
```

Perhaps this kind of formatting could be put in to Debug?

**Comment by passcod** [comment]
This is probably a needed library upgrade to the latest version of bitflags, which seems to be better at this.

**Comment by passcod** [comment]
That will be done in v5 (which takes a different approach to events). Tests for it here: 5661ca0

**Comment by passcod** [comment]
This was done for v4 in #162
