### ISSUE TITLE
Support checking if a path is being watched

### ISSUE THREAD

**Issue by droundy** [passcod/notify#122]
As I can see, my options on 4.0.1 are either to (a) keep my own HashSet of paths and use that, or (b) unwatch and check for an Err result (and which one) and then rewatch.

An alternative approach would be to change the enum to report differently a watched file that was written to versus a watched directory that contains a file that was written to (or renamed, or whatever).

**Comment by passcod** [comment]
The backends themselves are pretty opaque currently. I would encourage (a) at this point, although I would accept a PR implementing this.
