### ISSUE TITLE
Event order

### ISSUE THREAD

**Issue by newpavlov** [passcod/notify#123]
Here I would like to list some potential surprises for unaware users of the library. (hope others will add to the list) Not sure if they must be fixed, but I guess it's better to have explicit decision regarding them and maybe some documentation. For now it was tested only on Ubuntu, but it would be good to check if described behavior consistent across platforms.

If I take a folder `foo` with the following content:
```
foo/bar/1.file
foo/bar/2.file
```

And will copy it into watched folder `notify` will produce the following events:
```
Create("/tracked_folder/foo/bar/1.file")
Create("/tracked_folder/foo/bar/2.file")
Create("/tracked_folder/foo")
```

Potential surprising points:

1. No event for creation of `bar` subfolder.
2. Reverse order of events, first creation of files, only after that creation of the parent folder

Also removing this folder results in the "direct" order of events, first files, then subfolder and last parent folder.

Replacing tracking file result in the `Create` (if source file is from outside) or `Rename` (if source inside the tracked folder) event without `Remove` for the replaced file.

Symlinks appear as a simple file. (Maybe add option for following symlinks?)

**Comment by passcod** [comment]
Hi, could you write that up as documentation, say in the README, and submit a PR? Issues are not really the place for docs.

(Also ordering behaviour is most likely _not_ consistent across platforms, and might not even be consistent across Linuxes, or even across separate invocations on the same system (depending on _how_ writes are performed), as we depend entirely on the native (kernel) facilities. The way kernels "see" filesystems and writes/accesses might be very surprising, and perhaps I should add a stronger message to the docs to _carefully_ read the platform documentation for the underlying systems. Notify provides _some_ abstraction, but doesn't change the nature of these APIs.)
