### ISSUE TITLE
Possible race condition on recursive watch under linux

### ISSUE THREAD

**Issue by cyrilchampier** [passcod/notify#124]
It seems there is a debounce problem on linux:
if a directory and a subdirectory are created very quickly, the second directory (and any file created in it) will be ignored.
(is it the time that the new recursive watch is created on "sub1" ?)

Code:
```rust
    mod test_notify_crate {
        use std::sync::mpsc::channel;
        use std::time::Duration;
        use std::thread::sleep;
        use std::fs::create_dir;
        use self::tempdir::TempDir;
        use notify::{Watcher, RecursiveMode, watcher, DebouncedEvent};

        extern crate tempdir;
        extern crate notify;

        #[test]
        fn good() {
            let tempdir = TempDir::new("kragle").unwrap();
            let path = tempdir.path();
            let (tx, rx) = channel();
            let mut watcher = watcher(tx.clone(), Duration::from_millis(100)).unwrap();
            sleep(Duration::from_millis(100));
            watcher.watch(path, RecursiveMode::Recursive).unwrap();

            create_dir(path.join("sub1")).unwrap();
            sleep(Duration::from_millis(50));
            create_dir(path.join("sub1").join("sub2")).unwrap();

            match rx.recv_timeout(Duration::from_millis(200)) {
                Ok(DebouncedEvent::Create(ref path)) => assert!(path.ends_with("sub1")),
                e => panic!("watch error: {:?}", e),
            }
            match rx.recv_timeout(Duration::from_millis(200)) {
                Ok(DebouncedEvent::Create(ref path)) => assert!(path.ends_with("sub2")),
                e => panic!("watch error: {:?}", e),
            }
        }

        #[test]
        fn bad() {
            let tempdir = TempDir::new("kragle").unwrap();
            let path = tempdir.path();
            let (tx, rx) = channel();
            let mut watcher = watcher(tx.clone(), Duration::from_millis(100)).unwrap();
            sleep(Duration::from_millis(100));
            watcher.watch(path, RecursiveMode::Recursive).unwrap();

            create_dir(path.join("sub1")).unwrap();
            // both directories are almost created at the same time
            //            sleep(Duration::from_millis(50));
            create_dir(path.join("sub1").join("sub2")).unwrap();

            match rx.recv_timeout(Duration::from_millis(200)) {
                Ok(DebouncedEvent::Create(ref path)) => assert!(path.ends_with("sub1")),
                e => panic!("watch error: {:?}", e),
            }
            match rx.recv_timeout(Duration::from_millis(200)) {
                Ok(DebouncedEvent::Create(ref path)) => assert!(path.ends_with("sub2")),
                e => panic!("watch error: {:?}", e),
            }
        }
    }
```

These 2 tests pass on MacOS, but the second fail on Linux.

**Comment by dfaust** [comment]
Thanks for the report, unfortunately this is _expected_ behavior.

> is it the time that the new recursive watch is created on "sub1" ?

Yes. On Linux recursive watches need to be created manually and this may take some time.

The [documentation](https://docs.rs/notify/4.0.1/notify/op/index.html#create) says:

Upon receiving a `Create` event for a directory, it is necessary to scan the newly created directory for contents. The directory can contain files or directories **if those contents were created before the directory could be watched**, or if the directory was moved into the watched directory.

**Comment by cyrilchampier** [comment]
There is no way to know if the directory is watched or not ?
If I create "watched_directory/subfolder1/subfolder2",
then (multiple seconds later) create a file in "subfolder2", the file wont be detected.
That means, as a user, i need to reimplement the whole recursivity by myself to be sure I dont loose any events.

There is no way that the scan is done on the crate, and the possible duplicated events will be removed by the debounce ?

**Comment by dfaust** [comment]
That is true. In that case `notify` should scan new directories and watch any existing sub directories.

Event though we could then emit `Create` events for everything we find, I guess we shouldn't because that behavior would differ from that of other platforms in case a directory is copied into the watched folder. Which is why the point about having to scan the newly created directory anyway still stands.

**Comment by cyrilchampier** [comment]
If the only extra process from an user point of view is to "manually" trigger create if not already received, and not re-adding watches, the behaviour would be much more friendly indeed !

**Comment by dfaust** [comment]
I finally had time to look at this and realized, that newly created directories are already scanned for sub directories (https://github.com/passcod/notify/blob/v4.0.1/src/inotify/mod.rs#L282-L285).
I tested it and it works for me.

@cyrilchampier: Can you confirm that new directories are always watched? If not, can you provide a code example that shows it not working.

**Comment by cyrilchampier** [comment]
@dfaust I retried with a test, and cannot reproduce the problem,
this works perfectly: https://gist.github.com/cyrilchampier/dcf1c663017b17b4d90708494d763c52
I do clearly remember creating manually files (with touch) that was not detected, but cannot exactly reproduce the steps, so I guess I was not creating them in the correct directory.
Very strange, sorry for having you searching for nothing :(

**Comment by dfaust** [comment]
@cyrilchampier no problem, good to hear that it works now.
