### ISSUE TITLE
Logging file watching

### ISSUE THREAD

**Issue by 0freeman00** [passcod/notify#125]
Hello, 

can i listen to all the changes on logger file ? 

i mean there won't be any overhead associated  with it right ?

**Comment by passcod** [comment]
You can indeed listen to events on a single file.

What kind of overhead do you mean? There will be a small CPU overhead from the processing we do with the events, and there's about (10 + the length of the file path) bytes memory overhead per watch, plus Notify's baseline usage.

**Comment by 0freeman00** [comment]
Ok that is good. I am looking for creating a library, that can listen to the changes of the log files, and will track certain kind of error messages, 

In case of any critical error message found, i need to perform some action. 

This `notify` i think will be the perfect fit for listening for file change events. 

right ?

**Comment by passcod** [comment]
Indeed.

<small>

As a note, Github issues are for _issues._ While questions seeking e.g. clarification on some aspect of Notify are on topic, general questions such as "is this library suitable for my project" are not. You can send me mail, ask on Twitter, etc.

For the "perfect fit"... Look. As far as I know, Notify is at the moment _the_ major contender in the "file change notification" space in Rust. If you want to watch file changes, Notify is probably right. However, every project is different, and I cannot comment on the appropriateness of one particular library choice for an arbitrary project I know next to nothing about. In my experience, the best way to figure out if something will work out, especially in software, is to try it.

</small>
