### ISSUE TITLE
Will it read the changes from file ?

### ISSUE THREAD

**Issue by 0freeman00** [passcod/notify#126]
hey, so will this lib, actually read from the file ? all the changes that took place? or no?

**Comment by passcod** [comment]
No. This library monitors the changes as reported by the filesystem. What this entails varies by what interface your kernel exposes, but generally tracks events such as file handles closing, writes, and metadata (dates, names) changes.

Look up your OS's documentation for [the particular subsystem in use per platform](https://github.com/passcod/notify#platforms).
