### ISSUE TITLE
Doesn't work with logging files.

### ISSUE THREAD

**Issue by 0eleven00** [passcod/notify#127]
Hello, i tried watching for logging file changes where file writes were happening throught golang's standard logger. 

`tail -f fileName` was showing all the changes that were happening, but not `notify`

**Comment by passcod** [comment]
Please provide:

- OS and versions
- any logs that might be relevant
- what you expected, in detail
- what you got instead, in detail
- if possible, a reproducible setup

**Comment by passcod** [comment]
Closing due to lack of response.
