### ISSUE TITLE
Unable to decode StreamFlags

### ISSUE THREAD

**Issue by mqudsi** [passcod/notify#128]
I think this may be that notify doesn't support a new feature in macOS High Sierra:

```rust
thread '<unnamed>' panicked at 'Unable to decode StreamFlags: 4293888', src/libcore/option.rs:File change notification: RawEvent { path: Some("/Users/mqudsi/Library/Messages/Attachments/b5/05/BA79380F-DDF7-43CD-9A6A-A878B7CCF20F"), op: Ok(CHMOD | CREATE), cookie: None }
819:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_failed
   9: <core::option::Option<T>>::expect
  10: notify::fsevent::callback
  11: implementation_callback_rpc
  12: _Xcallback_rpc
  13: FSEventsD2F_server
  14: FSEventsClientProcessMessageCallback
  15: __CFMachPortPerform
  16: __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__
  17: __CFRunLoopDoSource1
  18: __CFRunLoopRun
  19: CFRunLoopRunSpecific
  20: CFRunLoopRun
  21: notify::fsevent::FsEventWatcher::run::{{closure}}
```

**Comment by passcod** [comment]
I think this is more likely to be relevant on the upstream: https://github.com/octplane/fsevent-rust

**Comment by mqudsi** [comment]
Thanks. Reported here: https://github.com/octplane/fsevent-rust/issues/11

**Comment by mqudsi** [comment]
I think it's a bug for notify to panic here? Especially since there's no good way of catching this in the notify client.

**Comment by octplane** [comment]
Fixed in version 0.2.17 of the library. Let me know if this fixes the bug. Probably at some point, we should get more flexible with unknown flags...

**Comment by mqudsi** [comment]
Thanks @octplane. Updated on my end, and I'll post back if I experience any other flag issues.

@passcod I tried to sandbox the watcher in a new thread and then `.join()` to try and restart on crash, but that doesn't work since notify detaches from the calling thread.

**Comment by passcod** [comment]
I'll update the minimum req on fsevents and cut a new version, but for the wider bug of "notify shouldn't panic" I think I'll leave this open as Known Bug unless I get a PR for it, until I start #117 (current schedule is mid december).

**Comment by passcod** [comment]
Closing in favour of more general v5 tracking
