### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by newpavlov** [passcod/notify#130]
`cargo outdated -R` produces the following output:
```
Name      Project  Compat  Latest  Kind    Platform
----      -------  ------  ------  ----    --------
bitflags  0.7.0    ---     1.0.0   Normal  ---
inotify   0.3.0    ---     0.5.0   Normal  cfg(target_os = "linux")
mio       0.5.1    ---     0.6.11  Normal  cfg(target_os = "linux")
walkdir   0.1.8    ---     2.0.1   Normal  ---
```

`walkdir v2.01` seems compatible with `v0.1.8`, others will require code updates. Updated `mio` and `walkdir` will exclude `winapi` from the dependency tree on Linux target.

**Comment by passcod** [comment]
- Bitflags upgrade requires fairly extensive changes and will be breaking, so I'll fold in the next major
- Walkir upgrade is done in the next version (4.0.3)
- Inotify and mio upgrades are likely-non-breaking but need fairly large code updates, so will also be done later
