### ISSUE TITLE
Write FSEvent backend

### ISSUE THREAD

**Issue by passcod** [passcod/notify#139]
- [ ] Implement
- [ ] Test on at least the last two versions of macOS (ref #128 for issues under High Sierra)
- [ ] Document
- [ ] Add to tests
- [ ] Add to Notify (maintainer)

#### Want to help?

As there's no "Backend Implementor's Guide" right now, you'll need to read through raw docs and source to get an idea of what's needed.

Create a new subordinate crate:
- make a `backend-fsevent` folder;
- add a `Cargo.toml` with `name = "notify-backend-fsevent"`;
- add an entry in the root `Cargo.toml` for the new backend;
- put your code in `backend-fsevent/src/lib.rs`;
- add `backend-fsevents/tests/compliance.rs` and populate it as in other backends.

Refer to the Backend documentation in the source (or render it with `cargo doc` yourself for convenience):

- https://github.com/passcod/notify/blob/next/backend/src/backend.rs
- https://github.com/passcod/notify/blob/next/backend/src/lib.rs
- etc

Also look at existing Backends e.g. https://github.com/passcod/notify/blob/next/backend-inotify/src/lib.rs

Read the documentation on `futures::Stream`, especially `poll()` method description of semantics: https://docs.rs/futures/0.1.17/futures/stream/trait.Stream.html#tymethod.poll

When starting out, omit the `#![deny(missing_docs)]` and just get it building and working, first.

You'll need to use the [fsevent](https://github.com/octplane/fsevent-rust) crate.

When you've got something that works, add it to the tests:
- in `ci/cross-tests.sh`
- in `ci/script.sh`
- in `CONTRIBUTING.md`

Then create a Pull Request so the tests will run on Travis!

**Comment by passcod** [comment]
@cmyr

**Comment by cmyr** [comment]
Great, I'll dig into this in the next few days.

**Comment by passcod** [comment]
Thank you so much ❤️

**Comment by cmyr** [comment]
@passcod is there a good way to ping you with little questions I might have? Do you prefer an issue, or irc, or?

**Comment by passcod** [comment]
I'm on the Mozilla IRC, if that works? If I'm not there for some reason (I have a bouncer but who knows) a comment on here is okay.

**Comment by passcod** [comment]
Closing some v5 issues that are outdated and/or not actionable now.
