### ISSUE TITLE
Write tree polling backend

### ISSUE THREAD

**Issue by passcod** [passcod/notify#142]
I haven't quite figured out the details yet, so no friendly description and no help-wanted tag. Some notes:

Tree-based instead of list-based. Initialisation would build an in-memory tree of the watched path, then subsequent polls would check up on the file structure and emit changes into the Buffer.

The tree structure need not be directly crawled to a tree: we can use `walkdir` to do the actual walking of the tree and re-interpret its result (in the iter loop) into a tree (and compare/update the tree on subsequent walks). That lets `walkdir` handle the pesky details of walking file trees.

- Can detect creates and removes
- Can emit on size change
- Can emit on metadata change
- Can't emit on access
- Can automatically watch new folders
- Can follow symlinks (through `walkdir`)
- No trivial way to track (file) renames
- Tracking moves (path renames) is also non-trivial

The actual walking work (beyond initialisation?) should be done in a subthread (or more) and results pushed back to the thread or written to the Buffer. The `poll()` method would then only read-and-delete from the Buffer.

On some platforms/filesystems, we can perhaps rely on folder timestamps to figure out where not to look further?

> For the far future, adding some heuristic to detect file moves would be great — even beyond poll-watching. An application might be interested to know if files were moved before it starts up a fs watch or even use that information without watching the fs at all. So this should go into a separate crate.

**Comment by dfaust** [comment]
- Currently the fs is read by `walkdir` this has the advantage that some corner cases like symlink loops and file descriptor limits are already handled. When using a tree structure, it won't fit the flat `walkdir` concept anymore. The biggest problem I can see is detecting removes. So we have two options.

1. Implement some of `walkdir`'s functionalities our self and walk the fs recursively. (the walkdir code is relatively small, but of cause the devil is in the detail)
2. Map the flat structure from `walkdir` back to a tree structure. (adds complexity, but should be doable)

- I don't think we should be doing blocking I/O in a poll. `std::fs::read_dir` is blocking and there doesn't seem to be a non-blocking alternative. Therefore I would suggest doing that in a thread. This would emulate the behavior of the other back-ends and would lead to better predictability.

- For the far future, adding some heuristic to detect file moves would be great - even beyond poll-watching. An application might be interested to know if files were moved before it starts up a fs watch or even use that information without watching the fs at all. So this should go into a separate crate.

**Comment by passcod** [comment]
Also could do a port of the existing flat polling backend to start with.

**Comment by passcod** [comment]
Closing some v5 issues that are outdated and/or not actionable now.
