### ISSUE TITLE
Use latest fsevent in new osx backend

### ISSUE THREAD

**Issue by Marwes** [passcod/notify#152]
See https://github.com/octplane/fsevent-rust/pull/12. Since the fsevent backend is [undergoing a rewrite](https://github.com/passcod/notify/pull/144) I figured I would hold off on submitting a PR and just open an issue instead so that at least this does not be forgotten.

EDIT: cc @cmyr

**Comment by octplane** [comment]
- https://crates.io/crates/fsevent/0.2.18

**Comment by octplane** [comment]
Actually, `0.3.0` is the right version. I had to bump the major version of `-sys` because of an API breaking change.

**Comment by passcod** [comment]
This will have to be done after merging #144

**Comment by passcod** [comment]
Closing some vNext issues that are outdated and/or not actionable now. (See #144 for why, here.) I would accept a PR doing this for v4 / the current branch.
