### ISSUE TITLE
Use crossbeam-channel instead of stdlib

### ISSUE THREAD

**Issue by matklad** [passcod/notify#160]
Hi! My understanding is that currently `notify` hard-codes the usage of `std::mpsc`, and this is a bit unfortunate: there are many channel implementations in Rust (`crossbeam-channel` most notably), and the std version is not really great: it lacks `select`, which severally  restricts its applicability. 

It would be cool if `notify` had a `trait EventSink { fn send(&mut self, Event); }` and used that instead of any particular channel implementation. 

Though, for practical purposes, perhaps just betting on `crossbeam-channel` would be even better?

**Comment by passcod** [comment]
v4 is in maintenance only, v5 (aiming for end of this year) uses a significantly different architecture based on Tokio and Futures. Internally, v5 uses multiqueue channels for some plumbing which I believe use crossbeam. Externally, in v5 you'll just subscribe to a `Stream` which will plug into the kernel eventing as appropriate.

**Comment by matklad** [comment]
Excellent, that should be even better! Thanks!

**Comment by netvl** [comment]
If v5 is still some time away, are there any chance for this to be implemented in v4?

**Comment by passcod** [comment]
Hmm, I'll take an implementation if someone wants to. I may have time to do it myself this weekend, but I'm not going to commit on that (chances are that if I want to work on notify, I'll work on v5).

The remaining question I think would be whether to be generic over only the channel exposed through the public API (which would be simpler), or to be generic over every channel use inside this library (which would likely help the performance characteristic further than just the last hop, varying on internals).

**Comment by passcod** [comment]
Shifting this to be purely crossbeam-channel as originally proposed. If there's interest in making it generic I'm happy to take an implementation later.

**Comment by passcod** [comment]
Done in 735eee1

**Comment by matklad** [comment]
FWIW, I slowly coming to conclusion that accepting an `Box<dyn FnMut(T)>` is almost always better than returning an `Receiver<T>`. The former is more general, as `Box::new(|t| chan.send(t))` works, and you can put any channel and any buffering strategy you want, or use something like `futures::oneshot` instead.

**Comment by ctrlcctrlv** [comment]
Sorry, stupid and confused person here, if I'm using 4.x branch, what is the best way to start using Crossbeam channels? Is such even possible?
