### ISSUE TITLE
debounced watcher doesn't terminate

### ISSUE THREAD

**Issue by vemoo** [passcod/notify#169]
This code doesn't terminate: https://github.com/vemoo/notify/blob/a02645e73eb4b0ec3de5ae7774b2a59cf4dc33ca/tests/debounce.rs#L1117-L1125

The issue seems to be with the `WatchTimer` thread not terminating.
I've changed the code here https://github.com/vemoo/notify/commit/a02645e73eb4b0ec3de5ae7774b2a59cf4dc33ca and that way it terminates, but I'm not sure if there's a better way.

**Comment by matklad** [comment]
@passcod could you cut a minor release with this?

**Comment by passcod** [comment]
Soon, yes. I'm rolling another fix in, just gotta get the time and these current/next few days are very busy for me.

**Comment by passcod** [comment]
Released in 4.0.7.
