### ISSUE TITLE
Does notify work on /sys virtual filestore?

### ISSUE THREAD

**Issue by russel** [passcod/notify#171]
I am successfully using notify on /dev/dvb but trying to add a watcher to /sys/class/rc appears to result in no events. 
```rust
let (transmit_end, receive_end) = channel();
let mut watcher = raw_watcher(transmit_end).unwrap();
watcher.watch("/sys/class/rc", RecursiveMode::Recursive).unwrap();
```
is the set up code.

**Comment by passcod** [comment]
Not at this time. This is an inotify limitation as best I can tell.

**Comment by russel** [comment]
Thanks for the confirmation that I am on to a loser with this strategy. I was beginning to wonder if it was a (lack of) feature of the virtual filesystem and inotify. Time for a "Plan B". Hopefully in the future sysfs_notify will get connected in.

Thanks for making this crate. Even though this application is Linux-only notify is nice to use.

**Comment by passcod** [comment]
You can probably use the `select` call to wait on /sys and /proc
interfaces, by the way.

**Comment by russel** [comment]
poll definitely works, I haven't tried select. 

I didn't want to have two different ways of working, and there is an inherent coupling in the system I was avoiding that I can just take on board. This means I can just use notify which is nice.

Plan B was really an alternate Plan A. :-)
