### ISSUE TITLE
Less events with linux release builds?

### ISSUE THREAD

**Issue by emabee** [passcod/notify#207]
# Issue with notify 4.0.12, rustc 1.36 release builds on SUSE linux

I'm trying to get noticed if a file was edited, and want to reread it then.

There is a test that rewrites the file in two different ways:

## truncate and rewrite

```rust
        eprintln!("===== truncate and rewrite");
        {
            let mut file = std::fs::OpenOptions::new()
                .truncate(true)
                .write(true)
                .open(specfile)
                .unwrap();
            file.write_all("foofoofoofoo").unwrap();
        }
```

## rename and recreate

```rust
        eprintln!("===== behave like many editors: rename and recreate");
        {
            std::fs::rename(&specfile, "/example/spec.old").unwrap();
            let mut file = std::fs::OpenOptions::new()
                .create(true)
                .write(true)
                .open(specfile)
                .unwrap();
            file.write_all("barbarbarbar").unwrap();
        }
```

## Watching

In a parallel thread, the test waits for events:

```rust
    std::thread::Builder::new().spawn(move || {
        let (tx, rx) = std::sync::mpsc::channel();

        let mut watcher =
            watcher(tx, std::time::Duration::from_millis(100)).unwrap_or_else(|e| {
                eprintln!(
                    "Creating filesystem watcher for specfile failed with {:?}",
                    e
                );
                ::std::process::exit(-1);
            });

        // watch the spec file's parent folder
        if let Err(e) = watcher.watch(&specfile.parent().unwrap(), RecursiveMode::NonRecursive)
        {
            eprintln!(
                "watching the parent folder of the log spec file {:?} failed with {:?}",
                specfile, e
            );
            ::std::process::exit(-1);
        }

        loop {
            match rx.recv() {
                Ok(debounced_event) => {
                    match debounced_event {
                        DebouncedEvent::Create(ref path) | DebouncedEvent::Write(ref path) => {
                            if path.canonicalize().unwrap() == specfile {
                                eprintln!("re-reading specfile after {:?}", debounced_event);
                                reread_logspecfile(&mut handle, &specfile);
                            } else {
                                eprintln!(
                                    "event {:?} ignored because path {:?} does not match {:?}",
                                    debounced_event,
                                    path,
                                    specfile
                                );
                            }
                        }
                        _event => eprintln!("ignoring event {:?}", _event),
                    }
                }
                Err(e) => eprintln!("watch error: {:?}", e),
            }
        }
    })?;
```

## Where it works

The test works on windows, both with debug and release builds,
and it works on linux with debug builds.
You then get an output like this:

```text
===== truncate and rewrite
ignoring event NoticeWrite("/example/spec.txt")
re-reading specfile after Write("/example/spec.txt")
===== behave like many editors: rename and recreate
ignoring event NoticeWrite("/example/other.out")
ignoring event NoticeRemove("/example/spec.txt")
event Write("/example/other.out") ignored because path "/example/other.out" does not match "/example/spec.txt"
ignoring event Rename("/example/spec.txt", "/example/spec.old")
re-reading specfile after Create("/example/spec.txt")
ignoring event NoticeWrite("/example/other.out")
```

## Where it does not work

It does not work with release builds on linux!

```text
===== truncate and rewrite
===== behave like many editors: rename and recreate
ignoring event NoticeWrite("/example/other.out")
ignoring event NoticeRemove("/example/spec.txt")
event Write("/example/other.out") ignored because path "/example/other.out" does not match "/example/spec.txt"
ignoring event Rename("/example/spec.txt", "/example/spec.old")
re-reading specfile after Create("/example/spec.txt")
ignoring event NoticeWrite("/example/other.out")
```

The difference is that two events do not appear after "truncate and rewrite":

```text
NoticeWrite("/example/spec.txt")
Write("/example/spec.txt")
```

This does not seem to be related to timing - I played around a lot with various wait times etc. The result remains: linux release builds have an issue.

Is there a way to work around this issue?

**Comment by passcod** [comment]
I've added this truncate-write test to the suite and also enabled release mode tests globally, so we'll see if it appears... but running the tests locally I wasn't able to reproduce. Could you run the test suite from the `try-v4` branch with and without `--release` and report back?

**Comment by emabee** [comment]
Thanks a lot for the fast reaction! 
I did not manage to break your test, only mine...

One big difference is that my watcher is not in the main thread, as in your case.
My test updates the file in the main thread, and expects to receive the events in a spawned thread.
After updating the file, the main thread of the test pauses for some seconds.

I improved the output of the test so that it outputs timestamps. I now have a state of the test where it runs (even in release mode) quite often successfully, but not always.
If it is successful, then I can see that the NoticeWrite event comes within 1 millisecond, and the Write event after the DEBOUNCE_DELAY of 1 second.
If it is not successful, then I do not receive the NoticeWrite, not even within the much longer wait time of the main thread (e.g. 5 seconds), and also no Write event.

I need to stop for today, hope to continue soon...

**Comment by emabee** [comment]
Thinking about what I wrote yesterday helped me find the _real_ reason for my problem. Since the watcher is started asynchronously, I have to wait with the test logic in the main thread a little bit. A short std::thread::sleep() did the job, now the test runs deterministically and successful.

Sorry for bothering you!

**Comment by passcod** [comment]
Well, we added a test, that's always worth it :)
