### ISSUE TITLE
fsevent-sys update prevents this package from compiling

### ISSUE THREAD

**Issue by EverlastingBugstopper** [passcod/notify#211]
Realize that this package is abandoned but anybody attempting to install this right now won't be able to build due to breaking changes in `fsevent-sys`

@ashleygwilliams forked and fixed in this commit: https://github.com/ashleygwilliams/notify/commit/85094ac5e9d7ff624840098d9ff51653cbe90a60

We're fine for now bc of this fork - if anybody comes across this issue you can use the `notify-forked` crate as a drop-in replacement.

**Comment by EverlastingBugstopper** [comment]
No worries!! Thanks for taking a look, it's really really appreciated 😄

**Comment by mtak-** [comment]
2.1.0 has been yanked and 3.0.0 published. i think this can be closed

**Comment by EverlastingBugstopper** [comment]
Yup! Seems to be working :) :) :) :) :)
