### ISSUE TITLE
Runtime fallback to polling instead of compile-time

### ISSUE THREAD

**Issue by passcod** [passcod/notify#64]
From #60:

> Dynamic fallbacks (from FANotify to INotify, and from [any backend] to polling, etc) instead of at-compile-time

**Comment by maurizi** [comment]
:+1: Often times backend compatibility doesn't depend on the operating system, but on the _file_ system.

For example, INotify on Linux won't work for NFS, SAMBA shares, or Virtualbox shared folders (to name a few examples I know of).
Falling back to polling is better than having to know to that for a certain directory the `RecommendedWatcher` won't work.

**Comment by passcod** [comment]
Also, Linux being the OS makes no guarantee that INotify or FANotify is available in the kernel, etc. We could also imagine falling back to polling if the INotify watch limit is too low.

**Comment by passcod** [comment]
This is now done in v5 and a pretty core part. There's certainly more that could be explored relating to that but good first step. (Closing now instead of waiting for v5 release.)
