### ISSUE TITLE
Breaks: minimize public API

### ISSUE THREAD

**Issue by jwilm** [passcod/notify#66]
There's a few things that probably shouldn't be marked `pub`:
- Internal module layout. The watcher types (eg `FSEventWatcher`) are already reexported, and there's nothing else in the modules which a consumer cares about (or should have access to, really). Specifically, these modules should have pub removed, and the reexports should be favored:
  - `fsevent`
  - `null`
  - `op`
  - `poll`
- `fsevent::FsEventWatcher::run`
- `fsevent::FsEventWatcher::stop`
- `fsevent::FsEventWatcher::is_running`
- `fsevent::callback`

**Comment by passcod** [comment]
:+1:

**Comment by passcod** [comment]
Covered by v5.
