### ISSUE TITLE
Online documentation is a dead link

### ISSUE THREAD

**Issue by phaazon** [passcod/notify#94]

**Comment by HessiJames** [comment]
Thanks for reporting, I added a link to the new docs.rs site to the readme.
@passcod: The link on crates.io still has to be updated.

**Comment by HessiJames** [comment]
Ok, I just realized, that the link is in the cargo.toml and updated it too.
So we have to release a new version. How is your review of the debounce module coming? ;)

**Comment by passcod** [comment]
This has been released in 3.0.0. The docs.rs will take a wee while to update, but it should all be pointing there correctly now.
